In [4]:
import tensorflow.keras as keras
from tensorflow.keras import backend as K
# from keras import backend as K
from keras.layers.core import Dense, Activation
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image
from keras.models import Model
from keras.models import load_model
from keras.applications import imagenet_utils
from keras.applications import mobilenet
from keras.utils.generic_utils import CustomObjectScope
from keras.layers import Dense,GlobalAveragePooling2D
from keras.applications import MobileNet
from keras.applications.mobilenet import preprocess_input
import numpy as np
from IPython.display import Image
from keras.optimizers import Adam
from flask import Flask, render_template, request

app = Flask(__name__)

def prepare_image(file):
    file_path = 'images/'
    file.save(file_path + file.filename)
    img = image.load_img(file_path + file.filename, target_size=(224, 224))
    img_array = image.img_to_array(img)
    img_array_expanded_dims = np.expand_dims(img_array, axis=0)
    print(keras.applications.mobilenet.preprocess_input(img_array_expanded_dims))
    return keras.applications.mobilenet.preprocess_input(img_array_expanded_dims)

def return_predictions(file):
    preprocessed_image = prepare_image(file)
#     with CustomObjectScope({'relu6': mobilenet.relu6}):
    model = load_model("models/model.h5")
    print(model.summary)
    predictions = model.predict(preprocessed_image)
    results = imagenet_utils.decode_predictions(predictions)
    return results

@app.route('/')
def upload_file():
    return render_template('upload.html')

@app.route('/uploader', methods = ['POST','GET'])
def upload_file_1():
    if request.method == 'POST': 
        file = request.files['file']
        r = return_predictions(file)
        return 'file uploaded successfully'

if __name__ == '__main__':
    app.run(debug = False)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [19/Apr/2020 03:39:08] "GET / HTTP/1.1" 200 -
[2020-04-19 03:39:14,768] ERROR in app: Exception on /uploader [POST]
Traceback (most recent call last):
  File "/home/ashay/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ashay/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ashay/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ashay/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ashay/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ashay/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request


[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  ...

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]
